### ISSUE TITLE
swap_linear_with_float8_linear does not pipe skip_fqn_list, cur_fqn to recursion

### ISSUE THREAD

**Issue by yitzhaklevi** [pytorch-labs/float8_experimental#205]
Hey, 
as you can [see here](https://github.com/pytorch-labs/float8_experimental/blob/main/float8_experimental/float8_linear_utils.py#L94) those arguments are not piped during the recursive call.
effectively only top level model.named_children() can be ignored.

**Comment by awgu** [comment]
Some other enhancement to `swap_linear_with_float8_linear` (somewhat inspired by learnings from FSDP):
- The swap function should return `nn.Module` so that it can be called on a single `nn.Linear`.
- nit: `model` should be renamed to `module` because the swap function can be called on any module (may not be the overall model).
